public class CaseEWOVConstants {
    public static final String STAGE_1 = 'Stage 1';
    public static final String STAGE_2 = 'Stage 2';
    public static final String STAGE_3 = 'Stage 3';
    public static final String FINAL_STAGE = 'Final Stage';
	public static final String STAGE_1_SEARCH_KEY1 = 'Upgrade to Stage 1';
    public static final String STAGE_1_SEARCH_KEY2 = 'New Stage 1 Complaint';
   	public static final String STAGE_2_SEARCH_KEY1 = 'Upgrade to Stage 2';
    public static final String STAGE_2_SEARCH_KEY2 = 'New Stage 2 Complaint';
    public static final String STAGE_3_SEARCH_KEY = 'Upgrade to Stage 3';
    public static final String FINAL_STAGE_SEARCH_KEY = 'Upgrade to Final Stage';
}